-- User notification preferences
ALTER TABLE users ADD COLUMN IF NOT EXISTS notify_device_connect BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS notify_device_block BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS notify_license_expiry BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS notify_newsletter BOOLEAN NOT NULL DEFAULT FALSE;
